### ISSUE TITLE
new npm release?

### ISSUE THREAD

**Issue by evoactivity** [lolmaus/ember-element-query#13]
Currently I have `github:lolmaus/ember-element-query` in my package.json
Is there a reason the latest version hasn't been published to npm?

**Comment by lolmaus** [comment]
Hi!

There's a roadmap in the readme, quite a few things need to be done before this can be released.

Unfortunately, despite using this actively in work and personal projects, I have neglected those chores for quite a while.

Now that you've shown interest, I can take a stab at it. Wanna participate?

**Comment by evoactivity** [comment]
I should be able to spend some time on this over the next few weeks yes, I'm in the emberjs discord as "evo".

Looking at the roadmap what stands out is the typescript work, I'm brand new to typescript so would probably need some guidance on those tasks. I could probably help with setting up the CI using github actions. 

For the roadmap item "Expose types" would that be creating *d.ts files exporting the type definitions found in the current .ts files?
The typedoc stuff I assume would be adding [typedoc comments](https://typedoc.org/guides/doccomments/) through out the codebse and setting up a github action to generate the docs?

**Comment by lolmaus** [comment]
> I'm in the emberjs discord as "evo".

Could not find you.

I'm lolmaus#4170, though I might not respond immediately.

***

> I could probably help with setting up the CI using github actions.

Awesome!

***

> For the roadmap item "Expose types" would that be creating *d.ts files exporting the type definitions found in the current .ts files?

We should read the docs on `ember-cli-typescript` regarding usage in addons. Probably this can be automated.

***

> The typedoc stuff I assume would be adding typedoc comments through out the codebse and setting up a github action to generate the docs?

Yes, and also set up CI for generating the actual documentation. The tricky part is to have the documentation AND a demo app in the same distro.

**Comment by evoactivity** [comment]
Ok, I should have some time tomorrow afternoon, I'll fork the repo and look at getting the tests running on github then I'll do some reading on ember-cli-typescript :)

**Comment by lolmaus** [comment]
@evoactivity I've looked into the `ember-cli-typescript` readme and found no addon-specific instructions there.

I've learned that `ember-cli-typescript` has added a couple of scripts to the `package.json`, which should fire automatically on `yarn publish` and take care of everything.

Also, I was recommended to use `release-it` for the release process. I'll look into it eventually.

**Comment by simonihmig** [comment]
https://github.com/lolmaus/ember-element-query/blob/gen-4/CHANGELOG.md :tada:
